'use client'
import { cn } from '@/lib/utils'
import { Activity, TrendingUp, Zap, Shield, BarChart2, CheckCircle } from 'lucide-react'

const MODULES = [
  {
    icon: Activity,
    label: 'OI Divergence',
    max: 25,
    color: 'text-violet-400',
    bg: 'bg-violet-500/10 border-violet-500/20',
    description:
      'Tracks open interest vs price divergence. When OI rises sharply while price stagnates or falls, it signals trapped positions about to unwind — a reliable precursor to strong directional moves.',
  },
  {
    icon: TrendingUp,
    label: 'Funding Rate',
    max: 20,
    color: 'text-blue-400',
    bg: 'bg-blue-500/10 border-blue-500/20',
    description:
      'Extreme funding rates (positive or negative) indicate overleveraged positioning. When funding is deeply negative, shorts are paying longs — historically a strong mean-reversion long setup.',
  },
  {
    icon: Zap,
    label: 'Liquidation Flow',
    max: 25,
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10 border-yellow-500/20',
    description:
      'Monitors real-time long/short liquidation imbalances. A spike in one-sided liquidations clears weak hands and typically precedes a sharp reversal — we trade that institutional clean-up.',
  },
  {
    icon: BarChart2,
    label: 'Momentum',
    max: 20,
    color: 'text-brand',
    bg: 'bg-brand/10 border-brand/20',
    description:
      'Combines 1h and 4h price momentum with volume confirmation. Momentum signals must agree with the directional vote from other modules — no momentum = no trade.',
  },
  {
    icon: Shield,
    label: 'Volatility Quality',
    max: 10,
    color: 'text-long',
    bg: 'bg-long/10 border-long/20',
    description:
      'ATR-based volatility gate. Markets that are too quiet (dead) or too chaotic (extreme ATR) are filtered out. Only clean trending conditions pass this gate.',
  },
]

const HOW_IT_FIRES = [
  'All 5 modules score simultaneously on live market data (refreshed every 30s)',
  'Total score must reach ≥75/100 to generate a signal',
  'At least 2 modules must cast a "strong" directional vote in the same direction',
  'Conflicting strong signals between LONG and SHORT = NO TRADE',
  'Same asset cannot fire again within 30 minutes (cooldown)',
  'SL and TP levels are ATR-calibrated — wider in high-volatility, tighter in calm markets',
  '10-minute grace period after creation before SL/TP checks begin (avoids wick-outs)',
]

export default function HowItWorksPage() {
  return (
    <div className="max-w-3xl mx-auto space-y-10">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold text-white mb-2">How EOLAS Signals Work</h1>
        <p className="text-gray-400">
          Every signal is generated by a multi-factor engine that scores 5 independent market indicators.
          No black box — this page explains exactly how a signal fires.
        </p>
      </div>

      {/* Score system */}
      <div className="bg-surface-card border border-surface-border rounded-xl p-6">
        <h2 className="text-lg font-bold text-white mb-1">The Scoring System</h2>
        <p className="text-gray-400 text-sm mb-6">
          Each module contributes a score. The total determines signal quality. Below 75/100 = no signal.
        </p>
        <div className="space-y-4">
          {MODULES.map(mod => (
            <div key={mod.label} className={cn('rounded-xl border p-4', mod.bg)}>
              <div className="flex items-center justify-between mb-2">
                <div className="flex items-center gap-2.5">
                  <div className={cn('w-8 h-8 rounded-lg bg-surface-card flex items-center justify-center', mod.color)}>
                    <mod.icon className="w-4 h-4" />
                  </div>
                  <span className={cn('font-bold text-sm', mod.color)}>{mod.label}</span>
                </div>
                <span className="text-xs font-mono text-gray-400">max {mod.max} pts</span>
              </div>
              <p className="text-sm text-gray-300 leading-relaxed">{mod.description}</p>
            </div>
          ))}
        </div>

        {/* Score total */}
        <div className="mt-4 p-4 bg-surface-elevated rounded-xl border border-surface-border">
          <div className="flex items-center justify-between text-sm">
            <div className="space-y-1 text-gray-400">
              <div>OI Divergence + Funding Rate + Liquidation + Momentum + Volatility</div>
            </div>
            <div className="text-right shrink-0 ml-4">
              <div className="text-2xl font-bold font-mono text-white">= 100</div>
              <div className="text-[10px] text-gray-500">max points</div>
            </div>
          </div>
        </div>
      </div>

      {/* How it fires */}
      <div className="bg-surface-card border border-surface-border rounded-xl p-6">
        <h2 className="text-lg font-bold text-white mb-4">Signal Firing Rules</h2>
        <ul className="space-y-3">
          {HOW_IT_FIRES.map((rule, i) => (
            <li key={i} className="flex items-start gap-3 text-sm text-gray-300">
              <CheckCircle className="w-4 h-4 text-long shrink-0 mt-0.5" />
              {rule}
            </li>
          ))}
        </ul>
      </div>

      {/* TP / SL */}
      <div className="bg-surface-card border border-surface-border rounded-xl p-6">
        <h2 className="text-lg font-bold text-white mb-4">Take Profit & Stop Loss</h2>
        <div className="grid sm:grid-cols-3 gap-4 text-center">
          {[
            { label: 'Stop Loss',        pct: '3%',  desc: 'Default (widens in volatile markets)', color: 'text-short' },
            { label: 'Take Profit 1',    pct: '5%',  desc: 'First target — partial exit level',    color: 'text-long' },
            { label: 'Take Profit 2',    pct: '9%',  desc: 'Extended target — let winners run',    color: 'text-long' },
          ].map(t => (
            <div key={t.label} className="bg-surface-elevated rounded-xl p-4 border border-surface-border">
              <div className={cn('text-3xl font-bold font-mono mb-1', t.color)}>{t.pct}</div>
              <div className="text-sm font-semibold text-white mb-1">{t.label}</div>
              <div className="text-[11px] text-gray-500">{t.desc}</div>
            </div>
          ))}
        </div>
        <p className="text-xs text-gray-500 mt-4 text-center">
          In high-volatility conditions (ATR &gt; 2%), all levels automatically widen by up to 50% to account for natural price swings.
        </p>
      </div>

      {/* Outcome tracking */}
      <div className="bg-surface-card border border-surface-border rounded-xl p-6">
        <h2 className="text-lg font-bold text-white mb-2">How Outcomes Are Tracked</h2>
        <p className="text-gray-400 text-sm mb-4">
          Every signal is monitored in real-time against live market prices. Outcomes are determined automatically:
        </p>
        <div className="grid sm:grid-cols-3 gap-3">
          {[
            { label: 'TP1 Hit ✓',      desc: 'Price reached first target',        color: 'bg-long/10 text-long border-long/20' },
            { label: 'TP2 Hit ✓',      desc: 'Price reached extended target',     color: 'bg-long/10 text-long border-long/20' },
            { label: 'Stopped Out',    desc: 'Price hit stop loss',               color: 'bg-short/10 text-short border-short/20' },
            { label: 'Timed Out',      desc: 'Market did not move in 24h',        color: 'bg-gray-800 text-gray-400 border-gray-700' },
          ].map(o => (
            <div key={o.label} className={cn('rounded-lg border px-3 py-2.5 text-center', o.color)}>
              <div className="font-bold text-xs mb-0.5">{o.label}</div>
              <div className="text-[10px] opacity-70">{o.desc}</div>
            </div>
          ))}
        </div>
        <p className="text-xs text-gray-600 mt-4 text-center">
          Timed Out signals are not counted in win/loss stats — only clean TP or SL outcomes are tracked.
        </p>
      </div>

      {/* Disclaimer */}
      <p className="text-xs text-gray-600 text-center pb-4">
        EOLAS Signals are algorithmic indicators only. Not financial advice.
        Always do your own research and use appropriate position sizing.
      </p>
    </div>
  )
}
